import { NoticeDetail } from '@/components/notice/NoticeDetail';
import { ErrorCard } from '@/components/shared/ErrorCard';
import { getNoticeById } from '@/lib/api/server/notice.api';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '임대소문 - 공고상세',
  description: 'Generated by create next app',
};

export default async function Notice({
  params,
}: {
  params: Promise<{ noticeId: string }>;
}) {
  const { noticeId } = await params;

  try {
    const notice = await getNoticeById(noticeId);

    return <NoticeDetail id={noticeId} notice={notice} />;
  } catch (error) {
    console.error('Failed to fetch notice:', error);

    return (
      <ErrorCard
        className="mx-4 my-2"
        content={
          '공고 상세를 불러오는 중 오류가 발생했어요\n잠시 후 다시 시도해주세요'
        }
      />
    );
  }
}
