import { Metadata } from 'next';
import { GetServerSideProps } from 'next';
import { NoticeBanner } from '@/components/home/NoticeBanner';
import { NoticeCard } from '@/components/home/NoticeCard';
import { InfoCard } from '@/components/shared/InfoCard';
import { ErrorCard } from '@/components/shared/ErrorCard';
import { NoticeCorporationTypeKor } from '@imdaesomun/shared/constants/notice';
import { fetchNotices } from '@/lib/fetchNotices';
import { Notice } from '@imdaesomun/shared/types/notice';

export const metadata: Metadata = {
  title: '임대소문 - 공공임대 정보 한눈에 보기',
  description: 'Generated by create next app',
};

export const getServerSideProps: GetServerSideProps = async () => {
  const [shNotices, ghNotices, ihNotices, bmcNotices] = await Promise.all([
    fetchNotices('sh'),
    fetchNotices('gh'),
    fetchNotices('ih'),
    fetchNotices('bmc'),
  ]);

  return {
    props: {
      shNotices,
      ghNotices,
      ihNotices,
      bmcNotices,
    },
  };
};

export default function Home({
  shNotices,
  ghNotices,
  ihNotices,
  bmcNotices,
}: any) {
  return (
    <div className="mx-4 my-2 flex flex-col items-stretch justify-start gap-2">
      <InfoCard content="최근 10개 공고만 제공되며, 과거 공고 및 검색·정렬 기능은 각 공사의 공식 홈페이지를 이용해주세요" />
      <div className="mb-24 grid grid-cols-1 gap-x-4 gap-y-8 p-4 md:grid-cols-2">
        {[
          { notices: shNotices, type: 'sh' },
          { notices: ghNotices, type: 'gh' },
          { notices: ihNotices, type: 'ih' },
          { notices: bmcNotices, type: 'bmc' },
        ].map(({ notices, type }) => (
          <div key={type} className="flex flex-col items-stretch gap-2">
            <NoticeBanner title={NoticeCorporationTypeKor[type]}>
              <div className={`icon-${type} w-7 md:w-8`} />
            </NoticeBanner>
            {notices.error ? (
              <ErrorCard content="공고를 불러오는 중 오류가 발생했어요\n잠시 후 다시 시도해주세요" />
            ) : (
              <div className="flex flex-col gap-2">
                {notices.data.map((notice: Notice) => (
                  <NoticeCard
                    key={notice.id}
                    id={notice.id}
                    title={notice.title}
                    date={notice.regDate}
                    views={notice.hits}
                    department={notice.department}
                  />
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
