import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '임대소문 - 공고상세',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="bg-sh h-full w-full">
      <span className="text-headline text-gray-900">공고상세</span>
    </div>
  );
}
