import type { Metadata } from 'next';
import './globals.css';
import { AppHeader } from '@/components/layouts/AppHeader';
import { AppNav } from '@/components/layouts/AppNav';
import { AppFooter } from '@/components/layouts/AppFooter';

export const metadata: Metadata = {
  title: '임대소문 - 공공임대 정보 한눈에 보기',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <div className="flex min-h-screen flex-col">
          <AppHeader />
          <main className="flex flex-1 flex-col">
            <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col">
              {children}
            </div>
          </main>
          <AppNav />
          <AppFooter />
        </div>
      </body>
    </html>
  );
}
