import type { Metadata } from 'next';
import './globals.css';
import AppHeader from '~/layouts/AppHeader';
import AppNav from '~/layouts/AppNav';
import AppFooter from '~/layouts/AppFooter';
import AppModalLayout from '~/layouts/AppModalLayout';
import AppLoading from '~/layouts/AppLoading';

export const metadata: Metadata = {
  title: '임대소문 - 공공임대 정보 한눈에 보기',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className="antialiased">
        <div className="flex min-h-screen flex-col">
          <AppModalLayout />
          <AppLoading />
          <AppHeader />
          <main className="flex flex-1 flex-col">
            <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col">
              {children}
            </div>
          </main>
          <AppNav />
          <AppFooter />
        </div>
      </body>
    </html>
  );
}
